import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getScheduleRun, reviewScheduleRun } from '../lib/api';
import { formatCurrency, formatDateTime } from '../lib/format';
import { useOperatorSession } from '../session/OperatorSessionContext';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { DetailList } from '../components/DetailList';
import { Field, TextArea } from '../components/ui/Field';
import { EmptyState, ErrorState, LoadingState } from '../components/ui/States';
import { Table, TableCell, TableRow } from '../components/ui/Table';
import { useAsyncData } from './useAsyncData';

function titleCase(value: string | null | undefined) {
  if (!value) {
    return 'Unclassified';
  }

  return value
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export function ScheduleRunDetailPage() {
  const { session } = useOperatorSession();
  const { runId } = useParams();
  const [refreshKey, setRefreshKey] = useState(0);
  const [reviewNotes, setReviewNotes] = useState('');
  const [reviewing, setReviewing] = useState(false);
  const [reviewError, setReviewError] = useState<string | null>(null);
  const { data, loading, error } = useAsyncData(() => getScheduleRun(session!, runId!), [refreshKey, runId, session]);

  if (loading) {
    return <LoadingState label="Loading schedule run…" />;
  }

  if (error !== null) {
    return <ErrorState title="Schedule run load failed" body={error} />;
  }

  if (data === null) {
    return <EmptyState title="Schedule run not found" body="The backend did not return this schedule run." />;
  }

  const variance = Number(data.variance);
  const alreadyReviewed = data.reconciliationStatus === 'reconciled' || data.reconciliationStatus === 'approved_with_variance';

  async function handleReview(resolution: 'reconciled' | 'approved_with_variance') {
    setReviewing(true);
    setReviewError(null);

    try {
      await reviewScheduleRun(session!, runId!, {
        resolution,
        notes: reviewNotes.trim() === '' ? undefined : reviewNotes
      });
      setReviewNotes('');
      setRefreshKey((value) => value + 1);
    } catch (cause) {
      setReviewError(cause instanceof Error ? cause.message : 'Schedule review failed.');
    } finally {
      setReviewing(false);
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <Link to="/schedules" className="text-sm font-semibold text-accent">
            Back to schedules
          </Link>
          <p className="mt-4 text-xs uppercase tracking-[0.18em] text-black/45">Schedule run</p>
          <h2 className="mt-2 font-serif text-4xl text-ink">{data.scheduleName ?? titleCase(data.scheduleType)}</h2>
          <p className="mt-3 max-w-3xl text-sm text-black/65">{data.scheduleDescription ?? 'Generated support schedule for balance sheet review.'}</p>
        </div>
        <Badge value={data.reconciliationStatus ?? data.status} className="self-start" />
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardContent className="py-5">
            <p className="text-xs uppercase tracking-[0.16em] text-black/45">GL balance</p>
            <p className="mt-2 text-2xl font-semibold text-ink">{formatCurrency(data.glBalance)}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="py-5">
            <p className="text-xs uppercase tracking-[0.16em] text-black/45">Schedule total</p>
            <p className="mt-2 text-2xl font-semibold text-ink">{formatCurrency(data.scheduleTotal)}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="py-5">
            <p className="text-xs uppercase tracking-[0.16em] text-black/45">Variance</p>
            <p className="mt-2 text-2xl font-semibold text-ink">{formatCurrency(data.variance)}</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Run metadata</CardTitle>
        </CardHeader>
        <CardContent>
          <DetailList
            items={[
              { label: 'Schedule type', value: titleCase(data.scheduleType) },
              { label: 'As of date', value: data.asOfDate },
              { label: 'Generated', value: formatDateTime(data.generatedAt) },
              { label: 'Generated by', value: [data.generatedByActorType, data.generatedByActorId].filter(Boolean).join(' · ') || 'Unknown' },
              { label: 'Reviewed', value: data.reviewedAt ? formatDateTime(data.reviewedAt) : 'Not reviewed' },
              { label: 'Generation strategy', value: titleCase(data.generationStrategy) },
              { label: 'Mapped GL accounts', value: data.glAccountIds.length === 0 ? 'None' : data.glAccountIds.join(', ') }
            ]}
          />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Review</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <DetailList
            items={[
              { label: 'Reconciliation status', value: titleCase(data.reconciliationStatus) },
              { label: 'Reviewed at', value: data.reconciliationReviewedAt ? formatDateTime(data.reconciliationReviewedAt) : 'Not reviewed' },
              { label: 'Reviewed by', value: data.reconciliationReviewedByUserId ?? 'Not reviewed' },
              { label: 'Review notes', value: data.reconciliationNotes ?? 'None' }
            ]}
          />
          {reviewError !== null ? <ErrorState title="Schedule review failed" body={reviewError} /> : null}
          {!alreadyReviewed ? (
            <div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end">
              <Field label="Review notes" hint={variance === 0 ? 'Optional for zero-variance schedules.' : 'Required when approving a variance.'}>
                <TextArea value={reviewNotes} onChange={(event) => setReviewNotes(event.target.value)} placeholder="Review conclusion" />
              </Field>
              <div className="flex flex-col gap-2 sm:flex-row">
                {variance === 0 ? (
                  <Button onClick={() => handleReview('reconciled')} disabled={reviewing}>
                    {reviewing ? 'Reviewing…' : 'Mark reconciled'}
                  </Button>
                ) : (
                  <Button onClick={() => handleReview('approved_with_variance')} disabled={reviewing}>
                    {reviewing ? 'Reviewing…' : 'Approve variance'}
                  </Button>
                )}
              </div>
            </div>
          ) : null}
        </CardContent>
      </Card>

      {data.rows.length === 0 ? (
        <EmptyState title="No support rows" body="This schedule run has no persisted support rows yet." />
      ) : (
        <Table columns={['#', 'Reference', 'Counterparty', 'Dates', 'Opening', 'Movement', 'Closing', 'Age']}>
          {data.rows.map((row) => (
            <TableRow key={row.scheduleRunRowId}>
              <TableCell>{row.rowOrder}</TableCell>
              <TableCell>
                <div className="font-semibold text-ink">{row.referenceNumber ?? row.referenceId ?? '—'}</div>
                <div className="text-xs text-black/55">{titleCase(row.referenceType)}</div>
              </TableCell>
              <TableCell>
                <div>{row.counterpartyName ?? '—'}</div>
                <div className="text-xs text-black/50">{row.counterpartyId ?? ''}</div>
              </TableCell>
              <TableCell>
                <div>{row.documentDate ?? 'No document date'}</div>
                <div className="text-xs text-black/50">{row.dueDate ? `Due ${row.dueDate}` : 'No due date'}</div>
              </TableCell>
              <TableCell className="text-right font-medium tabular-nums">{formatCurrency(row.openingAmount)}</TableCell>
              <TableCell className="text-right font-medium tabular-nums">{formatCurrency(row.movementAmount)}</TableCell>
              <TableCell className="text-right font-semibold tabular-nums text-ink">{formatCurrency(row.closingAmount)}</TableCell>
              <TableCell>{row.ageBucket ?? '—'}</TableCell>
            </TableRow>
          ))}
        </Table>
      )}
    </div>
  );
}
